[Appearance]
cursor_size=27
cursor_theme=Bibata-Modern-Ice

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\0\0\0\0\0\0\0\vb\0\0\x3_\0\0\x5\0\0\0\0\0\0\0\vb\0\0\x3_\0\0\0\0\0\0\0\0\x6\x86\0\0\x5\0\0\0\0\0\0\0\vb\0\0\x3_)
